-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Filter2D_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC );
end;


architecture behav of Filter2D_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_2D2 : STD_LOGIC_VECTOR (9 downto 0) := "1011010010";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_2D0 : STD_LOGIC_VECTOR (9 downto 0) := "1011010000";
    constant ap_const_lv10_2CF : STD_LOGIC_VECTOR (9 downto 0) := "1011001111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv11_59E : STD_LOGIC_VECTOR (10 downto 0) := "10110011110";
    constant ap_const_lv10_3FE : STD_LOGIC_VECTOR (9 downto 0) := "1111111110";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv10_3FD : STD_LOGIC_VECTOR (9 downto 0) := "1111111101";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv11_502 : STD_LOGIC_VECTOR (10 downto 0) := "10100000010";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_500 : STD_LOGIC_VECTOR (11 downto 0) := "010100000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_9FE : STD_LOGIC_VECTOR (11 downto 0) := "100111111110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv21_1171 : STD_LOGIC_VECTOR (20 downto 0) := "000000001000101110001";
    constant ap_const_lv19_3A8 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001110101000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal exitcond_reg_1308 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_i_reg_1317 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1273 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1264 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_dst_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal or_cond_i_reg_1338 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_027_0_i_reg_271 : STD_LOGIC_VECTOR (10 downto 0);
    signal exitcond7_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_V_fu_288_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_V_reg_1259 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_279_not_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_279_not_reg_1268 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1278 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_319_1_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_319_1_reg_1282 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_1286 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_430_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_16_reg_1293 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_13_1_t_fu_444_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_13_1_t_reg_1298 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_13_2_t_fu_458_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_13_2_t_reg_1303 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_condition_106 : BOOLEAN;
    signal ap_pipeline_reg_pp0_iter2_exitcond_reg_1308 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_474_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal or_cond_i_i_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_fu_600_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal x_reg_1321 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_29_fu_608_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_29_reg_1326 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_29_reg_1326 : STD_LOGIC_VECTOR (1 downto 0);
    signal brmerge_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_reg_1331 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_brmerge_reg_1331 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond_i_reg_1338 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter3_or_cond_i_reg_1338 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_buf_0_val_3_addr_reg_1342 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_addr_reg_1348 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_addr_reg_1354 : STD_LOGIC_VECTOR (10 downto 0);
    signal src_kernel_win_0_va_6_fu_755_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_6_reg_1360 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_7_fu_773_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_7_reg_1366 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_8_fu_791_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_8_reg_1372 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_26_0_1_fu_828_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_26_0_1_reg_1377 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_26_1_1_fu_1145_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Val2_26_1_1_reg_1382 : STD_LOGIC_VECTOR (20 downto 0);
    signal src_kernel_win_0_va_16_reg_1387 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_17_reg_1392 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_29_2_fu_980_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_29_2_reg_1397 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1170_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp5_reg_1402 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal p_Val2_s_87_fu_1137_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_s_87_reg_1407 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal k_buf_0_val_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce0 : STD_LOGIC;
    signal k_buf_0_val_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_3_ce1 : STD_LOGIC;
    signal k_buf_0_val_3_we1 : STD_LOGIC;
    signal k_buf_0_val_4_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce0 : STD_LOGIC;
    signal k_buf_0_val_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_4_ce1 : STD_LOGIC;
    signal k_buf_0_val_4_we1 : STD_LOGIC;
    signal k_buf_0_val_4_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce0 : STD_LOGIC;
    signal k_buf_0_val_5_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_ce1 : STD_LOGIC;
    signal k_buf_0_val_5_we1 : STD_LOGIC;
    signal k_buf_0_val_5_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_014_0_i_reg_260 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal col_assign_cast_fu_622_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal src_kernel_win_0_va_fu_140 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_1_fu_144 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_2_fu_148 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_3_fu_152 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_4_fu_156 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_5_fu_160 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_s_fu_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_fu_663_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_1_fu_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_2_fu_172 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_3_fu_176 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_1_0_fu_682_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_4_fu_180 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_5_fu_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_2_0_fu_701_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_306_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_4_fu_340_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_333_cast_cast_fu_346_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_362_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_14_1_fu_366_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_assign_14_1_cast_fu_372_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_14_2_fu_390_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_assign_s_fu_356_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_414_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_418_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_fu_422_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_16_1_fu_384_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_436_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_14_2_cast_fu_396_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_16_2_fu_408_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_450_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_fu_480_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_59_cast_fu_464_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_x_fu_496_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_20_fu_506_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_532_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_3_fu_540_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_p2_i_i_fu_546_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_assign_4_fu_564_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_x_cast_fu_502_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_assign_4_cast_fu_570_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_17_not_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_p2_i_i_cast_fu_554_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sel_tmp_fu_574_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp1_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_assign_6_t_fu_646_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_fu_651_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_670_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_689_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_744_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_762_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_fu_780_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl1_fu_804_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl2_fu_816_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl1_cast_fu_812_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl2_cast_fu_824_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_26_0_1_cast_fu_870_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_1151_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_shl3_fu_883_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl4_fu_895_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl3_cast_fu_891_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl4_cast_fu_903_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_26_1_fu_907_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_26_1_cast_fu_913_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_shl5_fu_921_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl6_fu_932_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl5_cast_fu_928_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl6_cast_fu_939_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_26_1_2_fu_943_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_26_1_2_cast_fu_949_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_29_0_2_cast_fu_880_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_348_1_cast_fu_917_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1162_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp4_cast_fu_967_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_348_1_2_cast_cas_fu_953_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp3_fu_970_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp3_cast_fu_976_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp2_fu_961_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_shl_fu_986_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl7_fu_998_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl_cast_fu_994_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl7_cast_fu_1006_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_26_2_1_fu_1010_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_26_2_1_cast_fu_1016_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp5_cast_fu_1050_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_29_2_cast_fu_1047_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_3_fu_1053_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_32_fu_1069_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_1_fu_1059_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_i_i_fu_1077_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_2_fu_1089_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_33_fu_1081_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_1095_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_Result_9_i_i_fu_1103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_1115_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal Range1_all_zeros_fu_1125_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_fu_1109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_not_i_i_fu_1131_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_26_1_1_fu_1145_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_26_1_1_fu_1145_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_1151_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1151_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1151_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_1151_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_1162_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1162_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_1170_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1170_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_1170_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_1151_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_1151_p10 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_1151_p30 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_1162_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1170_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1170_p20 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_26_1_1_fu_1145_p00 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_condition_114 : BOOLEAN;
    signal ap_condition_905 : BOOLEAN;

    component image_filter_mux_hbi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component image_filter_mul_ibs IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component image_filter_ama_jbC IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component image_filter_mac_kbM IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        din2 : IN STD_LOGIC_VECTOR (20 downto 0);
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component image_filter_mac_lbW IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component Filter2D_1_k_buf_eOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    k_buf_0_val_3_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_3_address0,
        ce0 => k_buf_0_val_3_ce0,
        q0 => k_buf_0_val_3_q0,
        address1 => k_buf_0_val_3_addr_reg_1342,
        ce1 => k_buf_0_val_3_ce1,
        we1 => k_buf_0_val_3_we1,
        d1 => p_src_data_stream_V_dout);

    k_buf_0_val_4_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_4_address0,
        ce0 => k_buf_0_val_4_ce0,
        q0 => k_buf_0_val_4_q0,
        address1 => k_buf_0_val_4_addr_reg_1348,
        ce1 => k_buf_0_val_4_ce1,
        we1 => k_buf_0_val_4_we1,
        d1 => k_buf_0_val_4_d1);

    k_buf_0_val_5_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_5_address0,
        ce0 => k_buf_0_val_5_ce0,
        q0 => k_buf_0_val_5_q0,
        address1 => k_buf_0_val_5_addr_reg_1354,
        ce1 => k_buf_0_val_5_ce1,
        we1 => k_buf_0_val_5_we1,
        d1 => k_buf_0_val_5_d1);

    image_filter_mux_hbi_U25 : component image_filter_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => right_border_buf_0_s_fu_164,
        din2 => right_border_buf_0_1_fu_168,
        din3 => ap_const_lv8_0,
        din4 => col_assign_6_t_fu_646_p2,
        dout => tmp_19_fu_651_p5);

    image_filter_mux_hbi_U26 : component image_filter_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => right_border_buf_0_3_fu_176,
        din2 => right_border_buf_0_4_fu_180,
        din3 => ap_const_lv8_0,
        din4 => col_assign_6_t_fu_646_p2,
        dout => tmp_21_fu_670_p5);

    image_filter_mux_hbi_U27 : component image_filter_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => right_border_buf_0_5_fu_184,
        din2 => right_border_buf_0_2_fu_172,
        din3 => ap_const_lv8_0,
        din4 => col_assign_6_t_fu_646_p2,
        dout => tmp_22_fu_689_p5);

    image_filter_mux_hbi_U28 : component image_filter_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => col_buf_0_val_0_0_fu_663_p3,
        din2 => col_buf_0_val_1_0_fu_682_p3,
        din3 => col_buf_0_val_2_0_fu_701_p3,
        din4 => tmp_16_reg_1293,
        dout => tmp_23_fu_744_p5);

    image_filter_mux_hbi_U29 : component image_filter_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => col_buf_0_val_0_0_fu_663_p3,
        din2 => col_buf_0_val_1_0_fu_682_p3,
        din3 => col_buf_0_val_2_0_fu_701_p3,
        din4 => row_assign_13_1_t_reg_1298,
        dout => tmp_24_fu_762_p5);

    image_filter_mux_hbi_U30 : component image_filter_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => col_buf_0_val_0_0_fu_663_p3,
        din2 => col_buf_0_val_1_0_fu_682_p3,
        din3 => col_buf_0_val_2_0_fu_701_p3,
        din4 => row_assign_13_2_t_reg_1303,
        dout => tmp_25_fu_780_p5);

    image_filter_mul_ibs_U31 : component image_filter_mul_ibs
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 14,
        dout_WIDTH => 21)
    port map (
        din0 => p_Val2_26_1_1_fu_1145_p0,
        din1 => p_Val2_26_1_1_fu_1145_p1,
        dout => p_Val2_26_1_1_fu_1145_p2);

    image_filter_ama_jbC_U32 : component image_filter_ama_jbC
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 11,
        din3_WIDTH => 24,
        dout_WIDTH => 25)
    port map (
        din0 => grp_fu_1151_p0,
        din1 => grp_fu_1151_p1,
        din2 => grp_fu_1151_p2,
        din3 => grp_fu_1151_p3,
        dout => grp_fu_1151_p4);

    image_filter_mac_kbM_U33 : component image_filter_mac_kbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        din2_WIDTH => 21,
        dout_WIDTH => 21)
    port map (
        din0 => grp_fu_1162_p0,
        din1 => grp_fu_1162_p1,
        din2 => p_Val2_26_1_1_reg_1382,
        dout => grp_fu_1162_p3);

    image_filter_mac_lbW_U34 : component image_filter_mac_lbW
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        din2_WIDTH => 24,
        dout_WIDTH => 25)
    port map (
        din0 => grp_fu_1170_p0,
        din1 => grp_fu_1170_p1,
        din2 => grp_fu_1170_p2,
        dout => grp_fu_1170_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = exitcond_fu_468_p2)))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_lv1_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = exitcond7_fu_282_p2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_lv1_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = exitcond7_fu_282_p2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_condition_114 = ap_const_boolean_1)) then
                    if (not((ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
                        ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                    elsif ((ap_const_logic_1 = ap_enable_reg_pp0_iter1)) then 
                        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif (((ap_const_lv1_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = exitcond7_fu_282_p2))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    p_014_0_i_reg_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state9))) then 
                p_014_0_i_reg_260 <= i_V_reg_1259;
            elsif (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then 
                p_014_0_i_reg_260 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    p_027_0_i_reg_271_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_0 = exitcond_fu_468_p2))) then 
                p_027_0_i_reg_271 <= j_V_fu_474_p2;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = exitcond7_fu_282_p2))) then 
                p_027_0_i_reg_271 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))))) then
                ap_pipeline_reg_pp0_iter1_brmerge_reg_1331 <= brmerge_reg_1331;
                ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 <= exitcond_reg_1308;
                ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317 <= or_cond_i_i_reg_1317;
                ap_pipeline_reg_pp0_iter1_or_cond_i_reg_1338 <= or_cond_i_reg_1338;
                ap_pipeline_reg_pp0_iter1_tmp_29_reg_1326 <= tmp_29_reg_1326;
                exitcond_reg_1308 <= exitcond_fu_468_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) then
                ap_pipeline_reg_pp0_iter2_exitcond_reg_1308 <= ap_pipeline_reg_pp0_iter1_exitcond_reg_1308;
                ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338 <= ap_pipeline_reg_pp0_iter1_or_cond_i_reg_1338;
                ap_pipeline_reg_pp0_iter3_or_cond_i_reg_1338 <= ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338;
                ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338 <= ap_pipeline_reg_pp0_iter3_or_cond_i_reg_1338;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and (ap_const_lv1_0 = exitcond_fu_468_p2))) then
                brmerge_reg_1331 <= brmerge_fu_612_p2;
                or_cond_i_i_reg_1317 <= or_cond_i_i_fu_526_p2;
                or_cond_i_reg_1338 <= or_cond_i_fu_617_p2;
                tmp_29_reg_1326 <= tmp_29_fu_608_p1;
                x_reg_1321 <= x_fu_600_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state2))) then
                i_V_reg_1259 <= i_V_fu_288_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = exitcond7_fu_282_p2))) then
                icmp_reg_1273 <= icmp_fu_316_p2;
                row_assign_13_1_t_reg_1298 <= row_assign_13_1_t_fu_444_p2;
                row_assign_13_2_t_reg_1303 <= row_assign_13_2_t_fu_458_p2;
                tmp_16_reg_1293 <= tmp_16_fu_430_p2;
                tmp_279_not_reg_1268 <= tmp_279_not_fu_300_p2;
                tmp_2_reg_1278 <= tmp_2_fu_322_p2;
                tmp_319_1_reg_1282 <= tmp_319_1_fu_328_p2;
                tmp_3_reg_1286 <= tmp_3_fu_334_p2;
                tmp_s_reg_1264 <= tmp_s_fu_294_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and (exitcond_reg_1308 = ap_const_lv1_0))) then
                k_buf_0_val_3_addr_reg_1342 <= col_assign_cast_fu_622_p1(11 - 1 downto 0);
                k_buf_0_val_4_addr_reg_1348 <= col_assign_cast_fu_622_p1(11 - 1 downto 0);
                k_buf_0_val_5_addr_reg_1354 <= col_assign_cast_fu_622_p1(11 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_reg_1338)))) then
                    p_Val2_26_0_1_reg_1377(19 downto 2) <= p_Val2_26_0_1_fu_828_p2(19 downto 2);
                p_Val2_26_1_1_reg_1382 <= p_Val2_26_1_1_fu_1145_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338)))) then
                p_Val2_29_2_reg_1397 <= p_Val2_29_2_fu_980_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter3_or_cond_i_reg_1338)))) then
                p_Val2_s_87_reg_1407 <= p_Val2_s_87_fu_1137_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))))) then
                right_border_buf_0_1_fu_168 <= right_border_buf_0_s_fu_164;
                right_border_buf_0_2_fu_172 <= right_border_buf_0_5_fu_184;
                right_border_buf_0_3_fu_176 <= col_buf_0_val_1_0_fu_682_p3;
                right_border_buf_0_4_fu_180 <= right_border_buf_0_3_fu_176;
                right_border_buf_0_5_fu_184 <= col_buf_0_val_2_0_fu_701_p3;
                right_border_buf_0_s_fu_164 <= col_buf_0_val_0_0_fu_663_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))))) then
                src_kernel_win_0_va_16_reg_1387 <= src_kernel_win_0_va_2_fu_148;
                src_kernel_win_0_va_17_reg_1392 <= src_kernel_win_0_va_4_fu_156;
                src_kernel_win_0_va_6_reg_1360 <= src_kernel_win_0_va_6_fu_755_p3;
                src_kernel_win_0_va_7_reg_1366 <= src_kernel_win_0_va_7_fu_773_p3;
                src_kernel_win_0_va_8_reg_1372 <= src_kernel_win_0_va_8_fu_791_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter2_exitcond_reg_1308))) then
                src_kernel_win_0_va_1_fu_144 <= src_kernel_win_0_va_fu_140;
                src_kernel_win_0_va_3_fu_152 <= src_kernel_win_0_va_16_reg_1387;
                src_kernel_win_0_va_5_fu_160 <= src_kernel_win_0_va_17_reg_1392;
                src_kernel_win_0_va_fu_140 <= src_kernel_win_0_va_6_reg_1360;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))))) then
                src_kernel_win_0_va_2_fu_148 <= src_kernel_win_0_va_7_fu_773_p3;
                src_kernel_win_0_va_4_fu_156 <= src_kernel_win_0_va_8_fu_791_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338)) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3))) then
                tmp5_reg_1402 <= grp_fu_1170_p3;
            end if;
        end if;
    end process;
    p_Val2_26_0_1_reg_1377(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, exitcond7_fu_282_p2, ap_condition_106, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (not((ap_const_lv1_0 = exitcond7_fu_282_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter4)))) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter1)) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter3)))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter4))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter1)) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter3))))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
        ImagLoc_x_cast_fu_502_p1 <= std_logic_vector(resize(signed(ImagLoc_x_fu_496_p2),13));

    ImagLoc_x_fu_496_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(tmp_59_cast_fu_464_p1));
    Range1_all_zeros_fu_1125_p2 <= "1" when (tmp_26_fu_1115_p4 = ap_const_lv5_0) else "0";
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2 downto 2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1 downto 1);
    ap_CS_fsm_state9 <= ap_CS_fsm(3 downto 3);

    ap_condition_106_assign_proc : process(p_src_data_stream_V_empty_n, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317, icmp_reg_1273, tmp_s_reg_1264)
    begin
                ap_condition_106 <= (((ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and (ap_const_lv1_0 = icmp_reg_1273) and (p_src_data_stream_V_empty_n = ap_const_logic_0)) or ((ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)) and (p_src_data_stream_V_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_114_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, ap_condition_106)
    begin
                ap_condition_114 <= not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))));
    end process;


    ap_condition_905_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)
    begin
                ap_condition_905 <= ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, exitcond7_fu_282_p2, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1)) or ((ap_const_lv1_1 = ap_CS_fsm_state2) and not((ap_const_lv1_0 = exitcond7_fu_282_p2))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(exitcond7_fu_282_p2, ap_CS_fsm_state2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state2) and not((ap_const_lv1_0 = exitcond7_fu_282_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_fu_612_p2 <= (tmp_279_not_reg_1268 or tmp_14_fu_520_p2);
    brmerge_i_i_not_i_i_fu_1131_p2 <= (Range1_all_zeros_fu_1125_p2 and carry_fu_1109_p2);
    carry_fu_1109_p2 <= (tmp_34_fu_1095_p3 or not_Result_9_i_i_fu_1103_p2);
    col_assign_6_t_fu_646_p2 <= (ap_pipeline_reg_pp0_iter1_tmp_29_reg_1326 xor ap_const_lv2_3);
        col_assign_cast_fu_622_p1 <= std_logic_vector(resize(signed(x_reg_1321),32));

    col_buf_0_val_0_0_fu_663_p3 <= 
        k_buf_0_val_3_q0 when (ap_pipeline_reg_pp0_iter1_brmerge_reg_1331(0) = '1') else 
        tmp_19_fu_651_p5;
    col_buf_0_val_1_0_fu_682_p3 <= 
        k_buf_0_val_4_q0 when (ap_pipeline_reg_pp0_iter1_brmerge_reg_1331(0) = '1') else 
        tmp_21_fu_670_p5;
    col_buf_0_val_2_0_fu_701_p3 <= 
        k_buf_0_val_5_q0 when (ap_pipeline_reg_pp0_iter1_brmerge_reg_1331(0) = '1') else 
        tmp_22_fu_689_p5;
    exitcond7_fu_282_p2 <= "1" when (p_014_0_i_reg_260 = ap_const_lv10_2D2) else "0";
    exitcond_fu_468_p2 <= "1" when (p_027_0_i_reg_271 = ap_const_lv11_502) else "0";
    grp_fu_1151_p0 <= grp_fu_1151_p00(8 - 1 downto 0);
    grp_fu_1151_p00 <= std_logic_vector(resize(unsigned(src_kernel_win_0_va_5_fu_160),9));
    grp_fu_1151_p1 <= grp_fu_1151_p10(8 - 1 downto 0);
    grp_fu_1151_p10 <= std_logic_vector(resize(unsigned(src_kernel_win_0_va_8_reg_1372),9));
    grp_fu_1151_p2 <= ap_const_lv19_3A8(11 - 1 downto 0);
    grp_fu_1151_p3 <= grp_fu_1151_p30(24 - 1 downto 0);
    grp_fu_1151_p30 <= std_logic_vector(resize(unsigned(p_Val2_26_0_1_cast_fu_870_p1),25));
    grp_fu_1162_p0 <= grp_fu_1162_p00(8 - 1 downto 0);
    grp_fu_1162_p00 <= std_logic_vector(resize(unsigned(src_kernel_win_0_va_1_fu_144),19));
    grp_fu_1162_p1 <= ap_const_lv19_3A8(11 - 1 downto 0);
    grp_fu_1170_p0 <= grp_fu_1170_p00(8 - 1 downto 0);
    grp_fu_1170_p00 <= std_logic_vector(resize(unsigned(src_kernel_win_0_va_6_reg_1360),19));
    grp_fu_1170_p1 <= ap_const_lv19_3A8(11 - 1 downto 0);
    grp_fu_1170_p2 <= grp_fu_1170_p20(24 - 1 downto 0);
    grp_fu_1170_p20 <= std_logic_vector(resize(unsigned(p_Val2_26_2_1_cast_fu_1016_p1),25));
    i_V_fu_288_p2 <= std_logic_vector(unsigned(p_014_0_i_reg_260) + unsigned(ap_const_lv10_1));
    icmp1_fu_490_p2 <= "0" when (tmp_18_fu_480_p4 = ap_const_lv10_0) else "1";
    icmp_fu_316_p2 <= "0" when (tmp_6_fu_306_p4 = ap_const_lv9_0) else "1";
    j_V_fu_474_p2 <= std_logic_vector(unsigned(p_027_0_i_reg_271) + unsigned(ap_const_lv11_1));
    k_buf_0_val_3_address0 <= col_assign_cast_fu_622_p1(11 - 1 downto 0);

    k_buf_0_val_3_ce0_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, ap_CS_fsm_pp0_stage0, ap_condition_106, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
            k_buf_0_val_3_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_ce1_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317, icmp_reg_1273, tmp_s_reg_1264, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, tmp_2_reg_1278, ap_condition_106)
    begin
        if ((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and (ap_const_lv1_0 = icmp_reg_1273) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = tmp_2_reg_1278))))) then 
            k_buf_0_val_3_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_we1_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317, icmp_reg_1273, tmp_s_reg_1264, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, tmp_2_reg_1278, ap_condition_106)
    begin
        if ((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and (ap_const_lv1_0 = icmp_reg_1273) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = tmp_2_reg_1278))))) then 
            k_buf_0_val_3_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_4_address0 <= col_assign_cast_fu_622_p1(11 - 1 downto 0);

    k_buf_0_val_4_ce0_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, ap_CS_fsm_pp0_stage0, ap_condition_106, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
            k_buf_0_val_4_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_ce1_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317, icmp_reg_1273, tmp_s_reg_1264, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, tmp_319_1_reg_1282, ap_condition_106)
    begin
        if ((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and (ap_const_lv1_0 = icmp_reg_1273) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = tmp_319_1_reg_1282))))) then 
            k_buf_0_val_4_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_d1_assign_proc : process(p_src_data_stream_V_dout, icmp_reg_1273, tmp_s_reg_1264, tmp_319_1_reg_1282, k_buf_0_val_3_q0, ap_condition_905)
    begin
        if ((ap_condition_905 = ap_const_boolean_1)) then
            if ((not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)))) then 
                k_buf_0_val_4_d1 <= k_buf_0_val_3_q0;
            elsif (((ap_const_lv1_0 = icmp_reg_1273) and not((ap_const_lv1_0 = tmp_319_1_reg_1282)))) then 
                k_buf_0_val_4_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_4_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_4_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_4_we1_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317, icmp_reg_1273, tmp_s_reg_1264, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, tmp_319_1_reg_1282, ap_condition_106)
    begin
        if ((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and (ap_const_lv1_0 = icmp_reg_1273) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = tmp_319_1_reg_1282))))) then 
            k_buf_0_val_4_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_5_address0 <= col_assign_cast_fu_622_p1(11 - 1 downto 0);

    k_buf_0_val_5_ce0_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, ap_CS_fsm_pp0_stage0, ap_condition_106, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
            k_buf_0_val_5_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_ce1_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317, icmp_reg_1273, tmp_s_reg_1264, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, tmp_2_reg_1278, ap_condition_106)
    begin
        if ((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and (ap_const_lv1_0 = icmp_reg_1273) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = tmp_2_reg_1278))))) then 
            k_buf_0_val_5_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_d1_assign_proc : process(p_src_data_stream_V_dout, icmp_reg_1273, tmp_s_reg_1264, tmp_2_reg_1278, k_buf_0_val_4_q0, ap_condition_905)
    begin
        if ((ap_condition_905 = ap_const_boolean_1)) then
            if ((not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)))) then 
                k_buf_0_val_5_d1 <= k_buf_0_val_4_q0;
            elsif (((ap_const_lv1_0 = icmp_reg_1273) and not((ap_const_lv1_0 = tmp_2_reg_1278)))) then 
                k_buf_0_val_5_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_5_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_5_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_5_we1_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317, icmp_reg_1273, tmp_s_reg_1264, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, tmp_2_reg_1278, ap_condition_106)
    begin
        if ((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and (ap_const_lv1_0 = icmp_reg_1273) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))) and not((ap_const_lv1_0 = tmp_2_reg_1278))))) then 
            k_buf_0_val_5_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    not_Result_9_i_i_fu_1103_p2 <= (tmp_33_fu_1081_p3 xor ap_const_lv1_1);
    or_cond_i_fu_617_p2 <= (icmp_reg_1273 and icmp1_fu_490_p2);
    or_cond_i_i_fu_526_p2 <= (tmp_14_fu_520_p2 and rev_fu_514_p2);
    p_Val2_1_fu_1059_p4 <= p_Val2_3_fu_1053_p2(21 downto 14);
        p_Val2_26_0_1_cast_fu_870_p1 <= std_logic_vector(resize(signed(p_Val2_26_0_1_reg_1377),24));

    p_Val2_26_0_1_fu_828_p2 <= std_logic_vector(unsigned(p_shl1_cast_fu_812_p1) - unsigned(p_shl2_cast_fu_824_p1));
    p_Val2_26_1_1_fu_1145_p0 <= p_Val2_26_1_1_fu_1145_p00(8 - 1 downto 0);
    p_Val2_26_1_1_fu_1145_p00 <= std_logic_vector(resize(unsigned(src_kernel_win_0_va_2_fu_148),21));
    p_Val2_26_1_1_fu_1145_p1 <= ap_const_lv21_1171(14 - 1 downto 0);
        p_Val2_26_1_2_cast_fu_949_p1 <= std_logic_vector(resize(signed(p_Val2_26_1_2_fu_943_p2),24));

    p_Val2_26_1_2_fu_943_p2 <= std_logic_vector(unsigned(p_shl5_cast_fu_928_p1) - unsigned(p_shl6_cast_fu_939_p1));
        p_Val2_26_1_cast_fu_913_p1 <= std_logic_vector(resize(signed(p_Val2_26_1_fu_907_p2),24));

    p_Val2_26_1_fu_907_p2 <= std_logic_vector(unsigned(p_shl3_cast_fu_891_p1) - unsigned(p_shl4_cast_fu_903_p1));
        p_Val2_26_2_1_cast_fu_1016_p1 <= std_logic_vector(resize(signed(p_Val2_26_2_1_fu_1010_p2),24));

    p_Val2_26_2_1_fu_1010_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_994_p1) - unsigned(p_shl7_cast_fu_1006_p1));
    p_Val2_29_0_2_cast_fu_880_p1 <= std_logic_vector(resize(unsigned(grp_fu_1151_p4),26));
    p_Val2_29_2_cast_fu_1047_p1 <= std_logic_vector(resize(unsigned(p_Val2_29_2_reg_1397),27));
    p_Val2_29_2_fu_980_p2 <= std_logic_vector(unsigned(tmp3_cast_fu_976_p1) + unsigned(tmp2_fu_961_p2));
    p_Val2_2_fu_1089_p2 <= std_logic_vector(unsigned(p_Val2_1_fu_1059_p4) + unsigned(tmp_1_i_i_fu_1077_p1));
    p_Val2_3_fu_1053_p2 <= std_logic_vector(unsigned(tmp5_cast_fu_1050_p1) + unsigned(p_Val2_29_2_cast_fu_1047_p1));
    p_Val2_s_87_fu_1137_p3 <= 
        p_Val2_2_fu_1089_p2 when (brmerge_i_i_not_i_i_fu_1131_p2(0) = '1') else 
        ap_const_lv8_FF;
    p_assign_14_1_cast_fu_372_p2 <= (tmp_10_fu_362_p1 xor ap_const_lv2_2);
    p_assign_14_1_fu_366_p2 <= std_logic_vector(unsigned(p_014_0_i_reg_260) + unsigned(ap_const_lv10_3FE));
    p_assign_14_2_cast_fu_396_p2 <= std_logic_vector(unsigned(tmp_10_fu_362_p1) + unsigned(ap_const_lv2_1));
    p_assign_14_2_fu_390_p2 <= std_logic_vector(unsigned(p_014_0_i_reg_260) + unsigned(ap_const_lv10_3FD));
    p_assign_16_1_fu_384_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(p_assign_14_1_cast_fu_372_p2));
    p_assign_16_2_fu_408_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) - unsigned(tmp_10_fu_362_p1));
    p_assign_3_fu_540_p2 <= std_logic_vector(unsigned(ap_const_lv12_1) - unsigned(tmp_59_cast_fu_464_p1));
    p_assign_4_cast_fu_570_p1 <= std_logic_vector(resize(unsigned(p_assign_4_fu_564_p2),13));
    p_assign_4_fu_564_p2 <= std_logic_vector(signed(ap_const_lv12_9FE) - signed(p_p2_i_i_fu_546_p3));
    p_assign_s_fu_356_p2 <= std_logic_vector(signed(ap_const_lv11_59E) - signed(tmp_333_cast_cast_fu_346_p1));

    p_dst_data_stream_V_blk_n_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)))) then 
            p_dst_data_stream_V_blk_n <= p_dst_data_stream_V_full_n;
        else 
            p_dst_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_data_stream_V_din <= p_Val2_s_87_reg_1407;

    p_dst_data_stream_V_write_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, ap_condition_106)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0)))))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;

        p_p2_i_i_cast_fu_554_p1 <= std_logic_vector(resize(signed(p_p2_i_i_fu_546_p3),13));

    p_p2_i_i_fu_546_p3 <= 
        p_assign_3_fu_540_p2 when (tmp_28_fu_532_p3(0) = '1') else 
        ImagLoc_x_fu_496_p2;
    p_shl1_cast_fu_812_p1 <= std_logic_vector(resize(unsigned(p_shl1_fu_804_p3),20));
    p_shl1_fu_804_p3 <= (src_kernel_win_0_va_4_fu_156 & ap_const_lv11_0);
    p_shl2_cast_fu_824_p1 <= std_logic_vector(resize(unsigned(p_shl2_fu_816_p3),20));
    p_shl2_fu_816_p3 <= (src_kernel_win_0_va_4_fu_156 & ap_const_lv2_0);
    p_shl3_cast_fu_891_p1 <= std_logic_vector(resize(unsigned(p_shl3_fu_883_p3),20));
    p_shl3_fu_883_p3 <= (src_kernel_win_0_va_3_fu_152 & ap_const_lv11_0);
    p_shl4_cast_fu_903_p1 <= std_logic_vector(resize(unsigned(p_shl4_fu_895_p3),20));
    p_shl4_fu_895_p3 <= (src_kernel_win_0_va_3_fu_152 & ap_const_lv2_0);
    p_shl5_cast_fu_928_p1 <= std_logic_vector(resize(unsigned(p_shl5_fu_921_p3),20));
    p_shl5_fu_921_p3 <= (src_kernel_win_0_va_7_reg_1366 & ap_const_lv11_0);
    p_shl6_cast_fu_939_p1 <= std_logic_vector(resize(unsigned(p_shl6_fu_932_p3),20));
    p_shl6_fu_932_p3 <= (src_kernel_win_0_va_7_reg_1366 & ap_const_lv2_0);
    p_shl7_cast_fu_1006_p1 <= std_logic_vector(resize(unsigned(p_shl7_fu_998_p3),20));
    p_shl7_fu_998_p3 <= (src_kernel_win_0_va_fu_140 & ap_const_lv2_0);
    p_shl_cast_fu_994_p1 <= std_logic_vector(resize(unsigned(p_shl_fu_986_p3),20));
    p_shl_fu_986_p3 <= (src_kernel_win_0_va_fu_140 & ap_const_lv11_0);

    p_src_data_stream_V_blk_n_assign_proc : process(p_src_data_stream_V_empty_n, ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317, icmp_reg_1273, tmp_s_reg_1264)
    begin
        if ((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and (ap_const_lv1_0 = icmp_reg_1273)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264))))) then 
            p_src_data_stream_V_blk_n <= p_src_data_stream_V_empty_n;
        else 
            p_src_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_data_stream_V_read_assign_proc : process(p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_exitcond_reg_1308, ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317, icmp_reg_1273, tmp_s_reg_1264, ap_enable_reg_pp0_iter5, ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338, ap_condition_106)
    begin
        if ((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and (ap_const_lv1_0 = icmp_reg_1273) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 = ap_const_lv1_0) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317)) and not((ap_const_lv1_0 = icmp_reg_1273)) and not((ap_const_lv1_0 = tmp_s_reg_1264)) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_condition_106 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338)) and (p_dst_data_stream_V_full_n = ap_const_logic_0))))))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    rev_fu_514_p2 <= (tmp_20_fu_506_p3 xor ap_const_lv1_1);
    row_assign_13_1_t_fu_444_p2 <= (tmp_9_fu_436_p3 xor ap_const_lv2_3);
    row_assign_13_2_t_fu_458_p2 <= (tmp_1_fu_450_p3 xor ap_const_lv2_3);
    sel_tmp7_fu_588_p2 <= (tmp_20_fu_506_p3 or tmp_17_not_fu_582_p2);
    sel_tmp8_fu_594_p2 <= (tmp_17_fu_558_p2 and sel_tmp7_fu_588_p2);
    sel_tmp_fu_574_p3 <= 
        ImagLoc_x_cast_fu_502_p1 when (or_cond_i_i_fu_526_p2(0) = '1') else 
        p_assign_4_cast_fu_570_p1;
    src_kernel_win_0_va_6_fu_755_p3 <= 
        tmp_23_fu_744_p5 when (tmp_3_reg_1286(0) = '1') else 
        col_buf_0_val_0_0_fu_663_p3;
    src_kernel_win_0_va_7_fu_773_p3 <= 
        tmp_24_fu_762_p5 when (tmp_3_reg_1286(0) = '1') else 
        col_buf_0_val_1_0_fu_682_p3;
    src_kernel_win_0_va_8_fu_791_p3 <= 
        tmp_25_fu_780_p5 when (tmp_3_reg_1286(0) = '1') else 
        col_buf_0_val_2_0_fu_701_p3;
    tmp2_fu_961_p2 <= std_logic_vector(unsigned(p_Val2_29_0_2_cast_fu_880_p1) + unsigned(tmp_348_1_cast_fu_917_p1));
    tmp3_cast_fu_976_p1 <= std_logic_vector(resize(unsigned(tmp3_fu_970_p2),26));
    tmp3_fu_970_p2 <= std_logic_vector(unsigned(tmp4_cast_fu_967_p1) + unsigned(tmp_348_1_2_cast_cas_fu_953_p1));
    tmp4_cast_fu_967_p1 <= std_logic_vector(resize(unsigned(grp_fu_1162_p3),25));
    tmp5_cast_fu_1050_p1 <= std_logic_vector(resize(unsigned(tmp5_reg_1402),27));
    tmp_10_fu_362_p1 <= p_014_0_i_reg_260(2 - 1 downto 0);
    tmp_11_fu_414_p1 <= tmp_4_fu_340_p2(2 - 1 downto 0);
    tmp_12_fu_418_p1 <= p_assign_s_fu_356_p2(2 - 1 downto 0);
    tmp_14_fu_520_p2 <= "1" when (signed(ImagLoc_x_fu_496_p2) < signed(ap_const_lv12_500)) else "0";
    tmp_15_fu_422_p3 <= 
        tmp_11_fu_414_p1 when (tmp_5_fu_350_p2(0) = '1') else 
        tmp_12_fu_418_p1;
    tmp_16_fu_430_p2 <= (tmp_15_fu_422_p3 xor ap_const_lv2_3);
    tmp_17_fu_558_p2 <= "1" when (signed(p_p2_i_i_fu_546_p3) < signed(ap_const_lv12_500)) else "0";
    tmp_17_not_fu_582_p2 <= (tmp_14_fu_520_p2 xor ap_const_lv1_1);
    tmp_18_fu_480_p4 <= p_027_0_i_reg_271(10 downto 1);
    tmp_1_fu_450_p3 <= 
        p_assign_14_2_cast_fu_396_p2 when (tmp_8_fu_402_p2(0) = '1') else 
        p_assign_16_2_fu_408_p2;
    tmp_1_i_i_fu_1077_p1 <= std_logic_vector(resize(unsigned(tmp_32_fu_1069_p3),8));
    tmp_20_fu_506_p3 <= ImagLoc_x_fu_496_p2(11 downto 11);
    tmp_26_fu_1115_p4 <= p_Val2_3_fu_1053_p2(26 downto 22);
    tmp_279_not_fu_300_p2 <= "1" when (unsigned(p_014_0_i_reg_260) > unsigned(ap_const_lv10_2CF)) else "0";
    tmp_28_fu_532_p3 <= ImagLoc_x_fu_496_p2(11 downto 11);
    tmp_29_fu_608_p1 <= x_fu_600_p3(2 - 1 downto 0);
    tmp_2_fu_322_p2 <= "1" when (p_014_0_i_reg_260 = ap_const_lv10_1) else "0";
    tmp_319_1_fu_328_p2 <= "1" when (p_014_0_i_reg_260 = ap_const_lv10_0) else "0";
    tmp_32_fu_1069_p3 <= p_Val2_3_fu_1053_p2(13 downto 13);
    tmp_333_cast_cast_fu_346_p1 <= std_logic_vector(resize(unsigned(tmp_4_fu_340_p2),11));
    tmp_33_fu_1081_p3 <= p_Val2_3_fu_1053_p2(21 downto 21);
    tmp_348_1_2_cast_cas_fu_953_p1 <= std_logic_vector(resize(unsigned(p_Val2_26_1_2_cast_fu_949_p1),25));
    tmp_348_1_cast_fu_917_p1 <= std_logic_vector(resize(unsigned(p_Val2_26_1_cast_fu_913_p1),26));
    tmp_34_fu_1095_p3 <= p_Val2_2_fu_1089_p2(7 downto 7);
    tmp_3_fu_334_p2 <= "1" when (unsigned(p_014_0_i_reg_260) > unsigned(ap_const_lv10_2D0)) else "0";
    tmp_4_fu_340_p2 <= std_logic_vector(unsigned(p_014_0_i_reg_260) + unsigned(ap_const_lv10_3FF));
    tmp_59_cast_fu_464_p1 <= std_logic_vector(resize(unsigned(p_027_0_i_reg_271),12));
    tmp_5_fu_350_p2 <= "1" when (unsigned(tmp_4_fu_340_p2) < unsigned(ap_const_lv10_2D0)) else "0";
    tmp_6_fu_306_p4 <= p_014_0_i_reg_260(9 downto 1);
    tmp_7_fu_378_p2 <= "1" when (unsigned(p_assign_14_1_fu_366_p2) < unsigned(ap_const_lv10_2D0)) else "0";
    tmp_8_fu_402_p2 <= "1" when (unsigned(p_assign_14_2_fu_390_p2) < unsigned(ap_const_lv10_2D0)) else "0";
    tmp_9_fu_436_p3 <= 
        p_assign_14_1_cast_fu_372_p2 when (tmp_7_fu_378_p2(0) = '1') else 
        p_assign_16_1_fu_384_p2;
    tmp_s_fu_294_p2 <= "1" when (unsigned(p_014_0_i_reg_260) < unsigned(ap_const_lv10_2D0)) else "0";
    x_fu_600_p3 <= 
        p_p2_i_i_cast_fu_554_p1 when (sel_tmp8_fu_594_p2(0) = '1') else 
        sel_tmp_fu_574_p3;
end behav;
