// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 4'b1;
parameter    ap_ST_fsm_state2 = 4'b10;
parameter    ap_ST_fsm_pp0_stage0 = 4'b100;
parameter    ap_ST_fsm_state9 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv10_2D2 = 10'b1011010010;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv10_2D0 = 10'b1011010000;
parameter    ap_const_lv10_2CF = 10'b1011001111;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv10_3FF = 10'b1111111111;
parameter    ap_const_lv11_59E = 11'b10110011110;
parameter    ap_const_lv10_3FE = 10'b1111111110;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv10_3FD = 10'b1111111101;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv11_502 = 11'b10100000010;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv12_500 = 12'b10100000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv12_9FE = 12'b100111111110;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_1A = 32'b11010;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv21_1171 = 21'b1000101110001;
parameter    ap_const_lv19_3A8 = 19'b1110101000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] exitcond_reg_1308;
reg   [0:0] ap_pipeline_reg_pp0_iter1_exitcond_reg_1308;
reg   [0:0] or_cond_i_i_reg_1317;
reg   [0:0] ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317;
reg   [0:0] icmp_reg_1273;
reg   [0:0] tmp_s_reg_1264;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] or_cond_i_reg_1338;
reg   [0:0] ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338;
reg   [10:0] p_027_0_i_reg_271;
wire   [0:0] exitcond7_fu_282_p2;
wire   [0:0] ap_CS_fsm_state2;
wire   [9:0] i_V_fu_288_p2;
reg   [9:0] i_V_reg_1259;
wire   [0:0] tmp_s_fu_294_p2;
wire   [0:0] tmp_279_not_fu_300_p2;
reg   [0:0] tmp_279_not_reg_1268;
wire   [0:0] icmp_fu_316_p2;
wire   [0:0] tmp_2_fu_322_p2;
reg   [0:0] tmp_2_reg_1278;
wire   [0:0] tmp_319_1_fu_328_p2;
reg   [0:0] tmp_319_1_reg_1282;
wire   [0:0] tmp_3_fu_334_p2;
reg   [0:0] tmp_3_reg_1286;
wire   [1:0] tmp_16_fu_430_p2;
reg   [1:0] tmp_16_reg_1293;
wire   [1:0] row_assign_13_1_t_fu_444_p2;
reg   [1:0] row_assign_13_1_t_reg_1298;
wire   [1:0] row_assign_13_2_t_fu_458_p2;
reg   [1:0] row_assign_13_2_t_reg_1303;
wire   [0:0] exitcond_fu_468_p2;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg    ap_condition_106;
reg   [0:0] ap_pipeline_reg_pp0_iter2_exitcond_reg_1308;
wire   [10:0] j_V_fu_474_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_526_p2;
wire   [12:0] x_fu_600_p3;
reg   [12:0] x_reg_1321;
wire   [1:0] tmp_29_fu_608_p1;
reg   [1:0] tmp_29_reg_1326;
reg   [1:0] ap_pipeline_reg_pp0_iter1_tmp_29_reg_1326;
wire   [0:0] brmerge_fu_612_p2;
reg   [0:0] brmerge_reg_1331;
reg   [0:0] ap_pipeline_reg_pp0_iter1_brmerge_reg_1331;
wire   [0:0] or_cond_i_fu_617_p2;
reg   [0:0] ap_pipeline_reg_pp0_iter1_or_cond_i_reg_1338;
reg   [0:0] ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338;
reg   [0:0] ap_pipeline_reg_pp0_iter3_or_cond_i_reg_1338;
reg   [10:0] k_buf_0_val_3_addr_reg_1342;
reg   [10:0] k_buf_0_val_4_addr_reg_1348;
reg   [10:0] k_buf_0_val_5_addr_reg_1354;
wire   [7:0] src_kernel_win_0_va_6_fu_755_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_1360;
wire   [7:0] src_kernel_win_0_va_7_fu_773_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_1366;
wire   [7:0] src_kernel_win_0_va_8_fu_791_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_1372;
wire   [19:0] p_Val2_26_0_1_fu_828_p2;
reg   [19:0] p_Val2_26_0_1_reg_1377;
wire   [20:0] p_Val2_26_1_1_fu_1145_p2;
reg   [20:0] p_Val2_26_1_1_reg_1382;
reg   [7:0] src_kernel_win_0_va_16_reg_1387;
reg   [7:0] src_kernel_win_0_va_17_reg_1392;
wire   [25:0] p_Val2_29_2_fu_980_p2;
reg   [25:0] p_Val2_29_2_reg_1397;
wire   [24:0] grp_fu_1170_p3;
reg   [24:0] tmp5_reg_1402;
reg    ap_enable_reg_pp0_iter3;
wire   [7:0] p_Val2_s_87_fu_1137_p3;
reg   [7:0] p_Val2_s_87_reg_1407;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter4;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [9:0] p_014_0_i_reg_260;
wire   [0:0] ap_CS_fsm_state9;
wire  signed [31:0] col_assign_cast_fu_622_p1;
reg   [7:0] src_kernel_win_0_va_fu_140;
reg   [7:0] src_kernel_win_0_va_1_fu_144;
reg   [7:0] src_kernel_win_0_va_2_fu_148;
reg   [7:0] src_kernel_win_0_va_3_fu_152;
reg   [7:0] src_kernel_win_0_va_4_fu_156;
reg   [7:0] src_kernel_win_0_va_5_fu_160;
reg   [7:0] right_border_buf_0_s_fu_164;
wire   [7:0] col_buf_0_val_0_0_fu_663_p3;
reg   [7:0] right_border_buf_0_1_fu_168;
reg   [7:0] right_border_buf_0_2_fu_172;
reg   [7:0] right_border_buf_0_3_fu_176;
wire   [7:0] col_buf_0_val_1_0_fu_682_p3;
reg   [7:0] right_border_buf_0_4_fu_180;
reg   [7:0] right_border_buf_0_5_fu_184;
wire   [7:0] col_buf_0_val_2_0_fu_701_p3;
wire   [8:0] tmp_6_fu_306_p4;
wire   [9:0] tmp_4_fu_340_p2;
wire   [10:0] tmp_333_cast_cast_fu_346_p1;
wire   [1:0] tmp_10_fu_362_p1;
wire   [9:0] p_assign_14_1_fu_366_p2;
wire   [1:0] p_assign_14_1_cast_fu_372_p2;
wire   [9:0] p_assign_14_2_fu_390_p2;
wire   [10:0] p_assign_s_fu_356_p2;
wire   [0:0] tmp_5_fu_350_p2;
wire   [1:0] tmp_11_fu_414_p1;
wire   [1:0] tmp_12_fu_418_p1;
wire   [1:0] tmp_15_fu_422_p3;
wire   [0:0] tmp_7_fu_378_p2;
wire   [1:0] p_assign_16_1_fu_384_p2;
wire   [1:0] tmp_9_fu_436_p3;
wire   [0:0] tmp_8_fu_402_p2;
wire   [1:0] p_assign_14_2_cast_fu_396_p2;
wire   [1:0] p_assign_16_2_fu_408_p2;
wire   [1:0] tmp_1_fu_450_p3;
wire   [9:0] tmp_18_fu_480_p4;
wire   [11:0] tmp_59_cast_fu_464_p1;
wire   [11:0] ImagLoc_x_fu_496_p2;
wire   [0:0] tmp_20_fu_506_p3;
wire   [0:0] tmp_14_fu_520_p2;
wire   [0:0] rev_fu_514_p2;
wire   [0:0] tmp_28_fu_532_p3;
wire   [11:0] p_assign_3_fu_540_p2;
wire   [11:0] p_p2_i_i_fu_546_p3;
wire   [11:0] p_assign_4_fu_564_p2;
wire  signed [12:0] ImagLoc_x_cast_fu_502_p1;
wire   [12:0] p_assign_4_cast_fu_570_p1;
wire   [0:0] tmp_17_not_fu_582_p2;
wire   [0:0] tmp_17_fu_558_p2;
wire   [0:0] sel_tmp7_fu_588_p2;
wire   [0:0] sel_tmp8_fu_594_p2;
wire  signed [12:0] p_p2_i_i_cast_fu_554_p1;
wire   [12:0] sel_tmp_fu_574_p3;
wire   [0:0] icmp1_fu_490_p2;
wire   [1:0] col_assign_6_t_fu_646_p2;
wire   [7:0] tmp_19_fu_651_p5;
wire   [7:0] tmp_21_fu_670_p5;
wire   [7:0] tmp_22_fu_689_p5;
wire   [7:0] tmp_23_fu_744_p5;
wire   [7:0] tmp_24_fu_762_p5;
wire   [7:0] tmp_25_fu_780_p5;
wire   [18:0] p_shl1_fu_804_p3;
wire   [9:0] p_shl2_fu_816_p3;
wire   [19:0] p_shl1_cast_fu_812_p1;
wire   [19:0] p_shl2_cast_fu_824_p1;
wire  signed [23:0] p_Val2_26_0_1_cast_fu_870_p1;
wire   [24:0] grp_fu_1151_p4;
wire   [18:0] p_shl3_fu_883_p3;
wire   [9:0] p_shl4_fu_895_p3;
wire   [19:0] p_shl3_cast_fu_891_p1;
wire   [19:0] p_shl4_cast_fu_903_p1;
wire   [19:0] p_Val2_26_1_fu_907_p2;
wire  signed [23:0] p_Val2_26_1_cast_fu_913_p1;
wire   [18:0] p_shl5_fu_921_p3;
wire   [9:0] p_shl6_fu_932_p3;
wire   [19:0] p_shl5_cast_fu_928_p1;
wire   [19:0] p_shl6_cast_fu_939_p1;
wire   [19:0] p_Val2_26_1_2_fu_943_p2;
wire  signed [23:0] p_Val2_26_1_2_cast_fu_949_p1;
wire   [25:0] p_Val2_29_0_2_cast_fu_880_p1;
wire   [25:0] tmp_348_1_cast_fu_917_p1;
wire   [20:0] grp_fu_1162_p3;
wire   [24:0] tmp4_cast_fu_967_p1;
wire   [24:0] tmp_348_1_2_cast_cas_fu_953_p1;
wire   [24:0] tmp3_fu_970_p2;
wire   [25:0] tmp3_cast_fu_976_p1;
wire   [25:0] tmp2_fu_961_p2;
wire   [18:0] p_shl_fu_986_p3;
wire   [9:0] p_shl7_fu_998_p3;
wire   [19:0] p_shl_cast_fu_994_p1;
wire   [19:0] p_shl7_cast_fu_1006_p1;
wire   [19:0] p_Val2_26_2_1_fu_1010_p2;
wire  signed [23:0] p_Val2_26_2_1_cast_fu_1016_p1;
wire   [26:0] tmp5_cast_fu_1050_p1;
wire   [26:0] p_Val2_29_2_cast_fu_1047_p1;
wire   [26:0] p_Val2_3_fu_1053_p2;
wire   [0:0] tmp_32_fu_1069_p3;
wire   [7:0] p_Val2_1_fu_1059_p4;
wire   [7:0] tmp_1_i_i_fu_1077_p1;
wire   [7:0] p_Val2_2_fu_1089_p2;
wire   [0:0] tmp_33_fu_1081_p3;
wire   [0:0] tmp_34_fu_1095_p3;
wire   [0:0] not_Result_9_i_i_fu_1103_p2;
wire   [4:0] tmp_26_fu_1115_p4;
wire   [0:0] Range1_all_zeros_fu_1125_p2;
wire   [0:0] carry_fu_1109_p2;
wire   [0:0] brmerge_i_i_not_i_i_fu_1131_p2;
wire   [7:0] p_Val2_26_1_1_fu_1145_p0;
wire   [13:0] p_Val2_26_1_1_fu_1145_p1;
wire   [7:0] grp_fu_1151_p0;
wire   [7:0] grp_fu_1151_p1;
wire   [10:0] grp_fu_1151_p2;
wire   [23:0] grp_fu_1151_p3;
wire   [7:0] grp_fu_1162_p0;
wire   [10:0] grp_fu_1162_p1;
wire   [7:0] grp_fu_1170_p0;
wire   [10:0] grp_fu_1170_p1;
wire   [23:0] grp_fu_1170_p2;
reg   [3:0] ap_NS_fsm;
wire   [8:0] grp_fu_1151_p00;
wire   [8:0] grp_fu_1151_p10;
wire   [24:0] grp_fu_1151_p30;
wire   [18:0] grp_fu_1162_p00;
wire   [18:0] grp_fu_1170_p00;
wire   [24:0] grp_fu_1170_p20;
wire   [20:0] p_Val2_26_1_1_fu_1145_p00;
reg    ap_condition_114;
reg    ap_condition_905;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'b1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_1342),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_1348),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_1354),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U25(
    .din1(right_border_buf_0_s_fu_164),
    .din2(right_border_buf_0_1_fu_168),
    .din3(ap_const_lv8_0),
    .din4(col_assign_6_t_fu_646_p2),
    .dout(tmp_19_fu_651_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U26(
    .din1(right_border_buf_0_3_fu_176),
    .din2(right_border_buf_0_4_fu_180),
    .din3(ap_const_lv8_0),
    .din4(col_assign_6_t_fu_646_p2),
    .dout(tmp_21_fu_670_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U27(
    .din1(right_border_buf_0_5_fu_184),
    .din2(right_border_buf_0_2_fu_172),
    .din3(ap_const_lv8_0),
    .din4(col_assign_6_t_fu_646_p2),
    .dout(tmp_22_fu_689_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U28(
    .din1(col_buf_0_val_0_0_fu_663_p3),
    .din2(col_buf_0_val_1_0_fu_682_p3),
    .din3(col_buf_0_val_2_0_fu_701_p3),
    .din4(tmp_16_reg_1293),
    .dout(tmp_23_fu_744_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U29(
    .din1(col_buf_0_val_0_0_fu_663_p3),
    .din2(col_buf_0_val_1_0_fu_682_p3),
    .din3(col_buf_0_val_2_0_fu_701_p3),
    .din4(row_assign_13_1_t_reg_1298),
    .dout(tmp_24_fu_762_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U30(
    .din1(col_buf_0_val_0_0_fu_663_p3),
    .din2(col_buf_0_val_1_0_fu_682_p3),
    .din3(col_buf_0_val_2_0_fu_701_p3),
    .din4(row_assign_13_2_t_reg_1303),
    .dout(tmp_25_fu_780_p5)
);

image_filter_mul_ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 21 ))
image_filter_mul_ibs_U31(
    .din0(p_Val2_26_1_1_fu_1145_p0),
    .din1(p_Val2_26_1_1_fu_1145_p1),
    .dout(p_Val2_26_1_1_fu_1145_p2)
);

image_filter_ama_jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
image_filter_ama_jbC_U32(
    .din0(grp_fu_1151_p0),
    .din1(grp_fu_1151_p1),
    .din2(grp_fu_1151_p2),
    .din3(grp_fu_1151_p3),
    .dout(grp_fu_1151_p4)
);

image_filter_mac_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
image_filter_mac_kbM_U33(
    .din0(grp_fu_1162_p0),
    .din1(grp_fu_1162_p1),
    .din2(p_Val2_26_1_1_reg_1382),
    .dout(grp_fu_1162_p3)
);

image_filter_mac_lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
image_filter_mac_lbW_U34(
    .din0(grp_fu_1170_p0),
    .din1(grp_fu_1170_p1),
    .din2(grp_fu_1170_p2),
    .dout(grp_fu_1170_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == exitcond_fu_468_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond7_fu_282_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond7_fu_282_p2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((ap_condition_114 == 1'b1)) begin
            if (~(1'b1 == ap_enable_reg_pp0_iter1)) begin
                ap_enable_reg_pp0_iter3 <= 1'b0;
            end else if ((1'b1 == ap_enable_reg_pp0_iter1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond7_fu_282_p2))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_014_0_i_reg_260 <= i_V_reg_1259;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        p_014_0_i_reg_260 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b0 == exitcond_fu_468_p2))) begin
        p_027_0_i_reg_271 <= j_V_fu_474_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond7_fu_282_p2))) begin
        p_027_0_i_reg_271 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))))) begin
        ap_pipeline_reg_pp0_iter1_brmerge_reg_1331 <= brmerge_reg_1331;
        ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 <= exitcond_reg_1308;
        ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317 <= or_cond_i_i_reg_1317;
        ap_pipeline_reg_pp0_iter1_or_cond_i_reg_1338 <= or_cond_i_reg_1338;
        ap_pipeline_reg_pp0_iter1_tmp_29_reg_1326 <= tmp_29_reg_1326;
        exitcond_reg_1308 <= exitcond_fu_468_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) begin
        ap_pipeline_reg_pp0_iter2_exitcond_reg_1308 <= ap_pipeline_reg_pp0_iter1_exitcond_reg_1308;
        ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338 <= ap_pipeline_reg_pp0_iter1_or_cond_i_reg_1338;
        ap_pipeline_reg_pp0_iter3_or_cond_i_reg_1338 <= ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338;
        ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338 <= ap_pipeline_reg_pp0_iter3_or_cond_i_reg_1338;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & (1'b0 == exitcond_fu_468_p2))) begin
        brmerge_reg_1331 <= brmerge_fu_612_p2;
        or_cond_i_i_reg_1317 <= or_cond_i_i_fu_526_p2;
        or_cond_i_reg_1338 <= or_cond_i_fu_617_p2;
        tmp_29_reg_1326 <= tmp_29_fu_608_p1;
        x_reg_1321 <= x_fu_600_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1259 <= i_V_fu_288_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond7_fu_282_p2))) begin
        icmp_reg_1273 <= icmp_fu_316_p2;
        row_assign_13_1_t_reg_1298 <= row_assign_13_1_t_fu_444_p2;
        row_assign_13_2_t_reg_1303 <= row_assign_13_2_t_fu_458_p2;
        tmp_16_reg_1293 <= tmp_16_fu_430_p2;
        tmp_279_not_reg_1268 <= tmp_279_not_fu_300_p2;
        tmp_2_reg_1278 <= tmp_2_fu_322_p2;
        tmp_319_1_reg_1282 <= tmp_319_1_fu_328_p2;
        tmp_3_reg_1286 <= tmp_3_fu_334_p2;
        tmp_s_reg_1264 <= tmp_s_fu_294_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & (exitcond_reg_1308 == 1'b0))) begin
        k_buf_0_val_3_addr_reg_1342 <= col_assign_cast_fu_622_p1;
        k_buf_0_val_4_addr_reg_1348 <= col_assign_cast_fu_622_p1;
        k_buf_0_val_5_addr_reg_1354 <= col_assign_cast_fu_622_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_reg_1338))) begin
        p_Val2_26_0_1_reg_1377[19 : 2] <= p_Val2_26_0_1_fu_828_p2[19 : 2];
        p_Val2_26_1_1_reg_1382 <= p_Val2_26_1_1_fu_1145_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338))) begin
        p_Val2_29_2_reg_1397 <= p_Val2_29_2_fu_980_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == ap_pipeline_reg_pp0_iter3_or_cond_i_reg_1338))) begin
        p_Val2_s_87_reg_1407 <= p_Val2_s_87_fu_1137_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))))) begin
        right_border_buf_0_1_fu_168 <= right_border_buf_0_s_fu_164;
        right_border_buf_0_2_fu_172 <= right_border_buf_0_5_fu_184;
        right_border_buf_0_3_fu_176 <= col_buf_0_val_1_0_fu_682_p3;
        right_border_buf_0_4_fu_180 <= right_border_buf_0_3_fu_176;
        right_border_buf_0_5_fu_184 <= col_buf_0_val_2_0_fu_701_p3;
        right_border_buf_0_s_fu_164 <= col_buf_0_val_0_0_fu_663_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))))) begin
        src_kernel_win_0_va_16_reg_1387 <= src_kernel_win_0_va_2_fu_148;
        src_kernel_win_0_va_17_reg_1392 <= src_kernel_win_0_va_4_fu_156;
        src_kernel_win_0_va_6_reg_1360 <= src_kernel_win_0_va_6_fu_755_p3;
        src_kernel_win_0_va_7_reg_1366 <= src_kernel_win_0_va_7_fu_773_p3;
        src_kernel_win_0_va_8_reg_1372 <= src_kernel_win_0_va_8_fu_791_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'b0 == ap_pipeline_reg_pp0_iter2_exitcond_reg_1308))) begin
        src_kernel_win_0_va_1_fu_144 <= src_kernel_win_0_va_fu_140;
        src_kernel_win_0_va_3_fu_152 <= src_kernel_win_0_va_16_reg_1387;
        src_kernel_win_0_va_5_fu_160 <= src_kernel_win_0_va_17_reg_1392;
        src_kernel_win_0_va_fu_140 <= src_kernel_win_0_va_6_reg_1360;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))))) begin
        src_kernel_win_0_va_2_fu_148 <= src_kernel_win_0_va_7_fu_773_p3;
        src_kernel_win_0_va_4_fu_156 <= src_kernel_win_0_va_8_fu_791_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == ap_pipeline_reg_pp0_iter2_or_cond_i_reg_1338) & (1'b1 == ap_enable_reg_pp0_iter3))) begin
        tmp5_reg_1402 <= grp_fu_1170_p3;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & ~(1'b0 == exitcond7_fu_282_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ~(1'b0 == exitcond7_fu_282_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & (1'b0 == icmp_reg_1273) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == tmp_2_reg_1278)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & (1'b0 == icmp_reg_1273) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == tmp_2_reg_1278)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & (1'b0 == icmp_reg_1273) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == tmp_319_1_reg_1282)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_condition_905 == 1'b1)) begin
        if ((~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_319_1_reg_1282))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & (1'b0 == icmp_reg_1273) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == tmp_319_1_reg_1282)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & (1'b0 == icmp_reg_1273) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == tmp_2_reg_1278)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_condition_905 == 1'b1)) begin
        if ((~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_2_reg_1278))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & (1'b0 == icmp_reg_1273) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b0 == tmp_2_reg_1278)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & (1'b0 == icmp_reg_1273)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & (1'b0 == icmp_reg_1273) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)))))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (~(1'b0 == exitcond7_fu_282_p2)) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter5) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b1 == ap_enable_reg_pp0_iter4)) & ~((1'b1 == ap_enable_reg_pp0_iter2) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b1 == ap_enable_reg_pp0_iter3)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b1 == ap_enable_reg_pp0_iter5) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b1 == ap_enable_reg_pp0_iter4)) | ((1'b1 == ap_enable_reg_pp0_iter2) & ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0))) & ~(1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b1 == ap_enable_reg_pp0_iter3)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_fu_502_p1 = $signed(ImagLoc_x_fu_496_p2);

assign ImagLoc_x_fu_496_p2 = ($signed(ap_const_lv12_FFF) + $signed(tmp_59_cast_fu_464_p1));

assign Range1_all_zeros_fu_1125_p2 = ((tmp_26_fu_1115_p4 == ap_const_lv5_0) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state2 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_state9 = ap_CS_fsm[ap_const_lv32_3];

always @ (*) begin
    ap_condition_106 = (((ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & (1'b0 == icmp_reg_1273) & (p_src_data_stream_V_empty_n == 1'b0)) | ((ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317) & ~(1'b0 == icmp_reg_1273) & ~(1'b0 == tmp_s_reg_1264) & (p_src_data_stream_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_114 = ~(((1'b1 == ap_enable_reg_pp0_iter2) & (ap_condition_106 == 1'b1)) | ((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_or_cond_i_reg_1338) & (p_dst_data_stream_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_905 = ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter1_exitcond_reg_1308 == 1'b0) & ~(1'b0 == ap_pipeline_reg_pp0_iter1_or_cond_i_i_reg_1317));
end

assign brmerge_fu_612_p2 = (tmp_279_not_reg_1268 | tmp_14_fu_520_p2);

assign brmerge_i_i_not_i_i_fu_1131_p2 = (Range1_all_zeros_fu_1125_p2 & carry_fu_1109_p2);

assign carry_fu_1109_p2 = (tmp_34_fu_1095_p3 | not_Result_9_i_i_fu_1103_p2);

assign col_assign_6_t_fu_646_p2 = (ap_pipeline_reg_pp0_iter1_tmp_29_reg_1326 ^ ap_const_lv2_3);

assign col_assign_cast_fu_622_p1 = $signed(x_reg_1321);

assign col_buf_0_val_0_0_fu_663_p3 = ((ap_pipeline_reg_pp0_iter1_brmerge_reg_1331[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_19_fu_651_p5);

assign col_buf_0_val_1_0_fu_682_p3 = ((ap_pipeline_reg_pp0_iter1_brmerge_reg_1331[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_21_fu_670_p5);

assign col_buf_0_val_2_0_fu_701_p3 = ((ap_pipeline_reg_pp0_iter1_brmerge_reg_1331[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_22_fu_689_p5);

assign exitcond7_fu_282_p2 = ((p_014_0_i_reg_260 == ap_const_lv10_2D2) ? 1'b1 : 1'b0);

assign exitcond_fu_468_p2 = ((p_027_0_i_reg_271 == ap_const_lv11_502) ? 1'b1 : 1'b0);

assign grp_fu_1151_p0 = grp_fu_1151_p00;

assign grp_fu_1151_p00 = src_kernel_win_0_va_5_fu_160;

assign grp_fu_1151_p1 = grp_fu_1151_p10;

assign grp_fu_1151_p10 = src_kernel_win_0_va_8_reg_1372;

assign grp_fu_1151_p2 = ap_const_lv19_3A8;

assign grp_fu_1151_p3 = grp_fu_1151_p30;

assign grp_fu_1151_p30 = $unsigned(p_Val2_26_0_1_cast_fu_870_p1);

assign grp_fu_1162_p0 = grp_fu_1162_p00;

assign grp_fu_1162_p00 = src_kernel_win_0_va_1_fu_144;

assign grp_fu_1162_p1 = ap_const_lv19_3A8;

assign grp_fu_1170_p0 = grp_fu_1170_p00;

assign grp_fu_1170_p00 = src_kernel_win_0_va_6_reg_1360;

assign grp_fu_1170_p1 = ap_const_lv19_3A8;

assign grp_fu_1170_p2 = grp_fu_1170_p20;

assign grp_fu_1170_p20 = $unsigned(p_Val2_26_2_1_cast_fu_1016_p1);

assign i_V_fu_288_p2 = (p_014_0_i_reg_260 + ap_const_lv10_1);

assign icmp1_fu_490_p2 = ((tmp_18_fu_480_p4 != ap_const_lv10_0) ? 1'b1 : 1'b0);

assign icmp_fu_316_p2 = ((tmp_6_fu_306_p4 != ap_const_lv9_0) ? 1'b1 : 1'b0);

assign j_V_fu_474_p2 = (p_027_0_i_reg_271 + ap_const_lv11_1);

assign k_buf_0_val_3_address0 = col_assign_cast_fu_622_p1;

assign k_buf_0_val_4_address0 = col_assign_cast_fu_622_p1;

assign k_buf_0_val_5_address0 = col_assign_cast_fu_622_p1;

assign not_Result_9_i_i_fu_1103_p2 = (tmp_33_fu_1081_p3 ^ 1'b1);

assign or_cond_i_fu_617_p2 = (icmp_reg_1273 & icmp1_fu_490_p2);

assign or_cond_i_i_fu_526_p2 = (tmp_14_fu_520_p2 & rev_fu_514_p2);

assign p_Val2_1_fu_1059_p4 = {{p_Val2_3_fu_1053_p2[ap_const_lv32_15 : ap_const_lv32_E]}};

assign p_Val2_26_0_1_cast_fu_870_p1 = $signed(p_Val2_26_0_1_reg_1377);

assign p_Val2_26_0_1_fu_828_p2 = (p_shl1_cast_fu_812_p1 - p_shl2_cast_fu_824_p1);

assign p_Val2_26_1_1_fu_1145_p0 = p_Val2_26_1_1_fu_1145_p00;

assign p_Val2_26_1_1_fu_1145_p00 = src_kernel_win_0_va_2_fu_148;

assign p_Val2_26_1_1_fu_1145_p1 = ap_const_lv21_1171;

assign p_Val2_26_1_2_cast_fu_949_p1 = $signed(p_Val2_26_1_2_fu_943_p2);

assign p_Val2_26_1_2_fu_943_p2 = (p_shl5_cast_fu_928_p1 - p_shl6_cast_fu_939_p1);

assign p_Val2_26_1_cast_fu_913_p1 = $signed(p_Val2_26_1_fu_907_p2);

assign p_Val2_26_1_fu_907_p2 = (p_shl3_cast_fu_891_p1 - p_shl4_cast_fu_903_p1);

assign p_Val2_26_2_1_cast_fu_1016_p1 = $signed(p_Val2_26_2_1_fu_1010_p2);

assign p_Val2_26_2_1_fu_1010_p2 = (p_shl_cast_fu_994_p1 - p_shl7_cast_fu_1006_p1);

assign p_Val2_29_0_2_cast_fu_880_p1 = grp_fu_1151_p4;

assign p_Val2_29_2_cast_fu_1047_p1 = p_Val2_29_2_reg_1397;

assign p_Val2_29_2_fu_980_p2 = (tmp3_cast_fu_976_p1 + tmp2_fu_961_p2);

assign p_Val2_2_fu_1089_p2 = (p_Val2_1_fu_1059_p4 + tmp_1_i_i_fu_1077_p1);

assign p_Val2_3_fu_1053_p2 = (tmp5_cast_fu_1050_p1 + p_Val2_29_2_cast_fu_1047_p1);

assign p_Val2_s_87_fu_1137_p3 = ((brmerge_i_i_not_i_i_fu_1131_p2[0:0] === 1'b1) ? p_Val2_2_fu_1089_p2 : ap_const_lv8_FF);

assign p_assign_14_1_cast_fu_372_p2 = (tmp_10_fu_362_p1 ^ ap_const_lv2_2);

assign p_assign_14_1_fu_366_p2 = ($signed(p_014_0_i_reg_260) + $signed(ap_const_lv10_3FE));

assign p_assign_14_2_cast_fu_396_p2 = (tmp_10_fu_362_p1 + ap_const_lv2_1);

assign p_assign_14_2_fu_390_p2 = ($signed(p_014_0_i_reg_260) + $signed(ap_const_lv10_3FD));

assign p_assign_16_1_fu_384_p2 = ($signed(ap_const_lv2_2) - $signed(p_assign_14_1_cast_fu_372_p2));

assign p_assign_16_2_fu_408_p2 = (ap_const_lv2_1 - tmp_10_fu_362_p1);

assign p_assign_3_fu_540_p2 = (ap_const_lv12_1 - tmp_59_cast_fu_464_p1);

assign p_assign_4_cast_fu_570_p1 = p_assign_4_fu_564_p2;

assign p_assign_4_fu_564_p2 = ($signed(ap_const_lv12_9FE) - $signed(p_p2_i_i_fu_546_p3));

assign p_assign_s_fu_356_p2 = ($signed(ap_const_lv11_59E) - $signed(tmp_333_cast_cast_fu_346_p1));

assign p_dst_data_stream_V_din = p_Val2_s_87_reg_1407;

assign p_p2_i_i_cast_fu_554_p1 = $signed(p_p2_i_i_fu_546_p3);

assign p_p2_i_i_fu_546_p3 = ((tmp_28_fu_532_p3[0:0] === 1'b1) ? p_assign_3_fu_540_p2 : ImagLoc_x_fu_496_p2);

assign p_shl1_cast_fu_812_p1 = p_shl1_fu_804_p3;

assign p_shl1_fu_804_p3 = {{src_kernel_win_0_va_4_fu_156}, {ap_const_lv11_0}};

assign p_shl2_cast_fu_824_p1 = p_shl2_fu_816_p3;

assign p_shl2_fu_816_p3 = {{src_kernel_win_0_va_4_fu_156}, {ap_const_lv2_0}};

assign p_shl3_cast_fu_891_p1 = p_shl3_fu_883_p3;

assign p_shl3_fu_883_p3 = {{src_kernel_win_0_va_3_fu_152}, {ap_const_lv11_0}};

assign p_shl4_cast_fu_903_p1 = p_shl4_fu_895_p3;

assign p_shl4_fu_895_p3 = {{src_kernel_win_0_va_3_fu_152}, {ap_const_lv2_0}};

assign p_shl5_cast_fu_928_p1 = p_shl5_fu_921_p3;

assign p_shl5_fu_921_p3 = {{src_kernel_win_0_va_7_reg_1366}, {ap_const_lv11_0}};

assign p_shl6_cast_fu_939_p1 = p_shl6_fu_932_p3;

assign p_shl6_fu_932_p3 = {{src_kernel_win_0_va_7_reg_1366}, {ap_const_lv2_0}};

assign p_shl7_cast_fu_1006_p1 = p_shl7_fu_998_p3;

assign p_shl7_fu_998_p3 = {{src_kernel_win_0_va_fu_140}, {ap_const_lv2_0}};

assign p_shl_cast_fu_994_p1 = p_shl_fu_986_p3;

assign p_shl_fu_986_p3 = {{src_kernel_win_0_va_fu_140}, {ap_const_lv11_0}};

assign rev_fu_514_p2 = (tmp_20_fu_506_p3 ^ 1'b1);

assign row_assign_13_1_t_fu_444_p2 = (tmp_9_fu_436_p3 ^ ap_const_lv2_3);

assign row_assign_13_2_t_fu_458_p2 = (tmp_1_fu_450_p3 ^ ap_const_lv2_3);

assign sel_tmp7_fu_588_p2 = (tmp_20_fu_506_p3 | tmp_17_not_fu_582_p2);

assign sel_tmp8_fu_594_p2 = (tmp_17_fu_558_p2 & sel_tmp7_fu_588_p2);

assign sel_tmp_fu_574_p3 = ((or_cond_i_i_fu_526_p2[0:0] === 1'b1) ? ImagLoc_x_cast_fu_502_p1 : p_assign_4_cast_fu_570_p1);

assign src_kernel_win_0_va_6_fu_755_p3 = ((tmp_3_reg_1286[0:0] === 1'b1) ? tmp_23_fu_744_p5 : col_buf_0_val_0_0_fu_663_p3);

assign src_kernel_win_0_va_7_fu_773_p3 = ((tmp_3_reg_1286[0:0] === 1'b1) ? tmp_24_fu_762_p5 : col_buf_0_val_1_0_fu_682_p3);

assign src_kernel_win_0_va_8_fu_791_p3 = ((tmp_3_reg_1286[0:0] === 1'b1) ? tmp_25_fu_780_p5 : col_buf_0_val_2_0_fu_701_p3);

assign tmp2_fu_961_p2 = (p_Val2_29_0_2_cast_fu_880_p1 + tmp_348_1_cast_fu_917_p1);

assign tmp3_cast_fu_976_p1 = tmp3_fu_970_p2;

assign tmp3_fu_970_p2 = (tmp4_cast_fu_967_p1 + tmp_348_1_2_cast_cas_fu_953_p1);

assign tmp4_cast_fu_967_p1 = grp_fu_1162_p3;

assign tmp5_cast_fu_1050_p1 = tmp5_reg_1402;

assign tmp_10_fu_362_p1 = p_014_0_i_reg_260[1:0];

assign tmp_11_fu_414_p1 = tmp_4_fu_340_p2[1:0];

assign tmp_12_fu_418_p1 = p_assign_s_fu_356_p2[1:0];

assign tmp_14_fu_520_p2 = (($signed(ImagLoc_x_fu_496_p2) < $signed(12'b10100000000)) ? 1'b1 : 1'b0);

assign tmp_15_fu_422_p3 = ((tmp_5_fu_350_p2[0:0] === 1'b1) ? tmp_11_fu_414_p1 : tmp_12_fu_418_p1);

assign tmp_16_fu_430_p2 = (tmp_15_fu_422_p3 ^ ap_const_lv2_3);

assign tmp_17_fu_558_p2 = (($signed(p_p2_i_i_fu_546_p3) < $signed(12'b10100000000)) ? 1'b1 : 1'b0);

assign tmp_17_not_fu_582_p2 = (tmp_14_fu_520_p2 ^ 1'b1);

assign tmp_18_fu_480_p4 = {{p_027_0_i_reg_271[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_1_fu_450_p3 = ((tmp_8_fu_402_p2[0:0] === 1'b1) ? p_assign_14_2_cast_fu_396_p2 : p_assign_16_2_fu_408_p2);

assign tmp_1_i_i_fu_1077_p1 = tmp_32_fu_1069_p3;

assign tmp_20_fu_506_p3 = ImagLoc_x_fu_496_p2[ap_const_lv32_B];

assign tmp_26_fu_1115_p4 = {{p_Val2_3_fu_1053_p2[ap_const_lv32_1A : ap_const_lv32_16]}};

assign tmp_279_not_fu_300_p2 = ((p_014_0_i_reg_260 > ap_const_lv10_2CF) ? 1'b1 : 1'b0);

assign tmp_28_fu_532_p3 = ImagLoc_x_fu_496_p2[ap_const_lv32_B];

assign tmp_29_fu_608_p1 = x_fu_600_p3[1:0];

assign tmp_2_fu_322_p2 = ((p_014_0_i_reg_260 == ap_const_lv10_1) ? 1'b1 : 1'b0);

assign tmp_319_1_fu_328_p2 = ((p_014_0_i_reg_260 == ap_const_lv10_0) ? 1'b1 : 1'b0);

assign tmp_32_fu_1069_p3 = p_Val2_3_fu_1053_p2[ap_const_lv32_D];

assign tmp_333_cast_cast_fu_346_p1 = tmp_4_fu_340_p2;

assign tmp_33_fu_1081_p3 = p_Val2_3_fu_1053_p2[ap_const_lv32_15];

assign tmp_348_1_2_cast_cas_fu_953_p1 = $unsigned(p_Val2_26_1_2_cast_fu_949_p1);

assign tmp_348_1_cast_fu_917_p1 = $unsigned(p_Val2_26_1_cast_fu_913_p1);

assign tmp_34_fu_1095_p3 = p_Val2_2_fu_1089_p2[ap_const_lv32_7];

assign tmp_3_fu_334_p2 = ((p_014_0_i_reg_260 > ap_const_lv10_2D0) ? 1'b1 : 1'b0);

assign tmp_4_fu_340_p2 = ($signed(p_014_0_i_reg_260) + $signed(ap_const_lv10_3FF));

assign tmp_59_cast_fu_464_p1 = p_027_0_i_reg_271;

assign tmp_5_fu_350_p2 = ((tmp_4_fu_340_p2 < ap_const_lv10_2D0) ? 1'b1 : 1'b0);

assign tmp_6_fu_306_p4 = {{p_014_0_i_reg_260[ap_const_lv32_9 : ap_const_lv32_1]}};

assign tmp_7_fu_378_p2 = ((p_assign_14_1_fu_366_p2 < ap_const_lv10_2D0) ? 1'b1 : 1'b0);

assign tmp_8_fu_402_p2 = ((p_assign_14_2_fu_390_p2 < ap_const_lv10_2D0) ? 1'b1 : 1'b0);

assign tmp_9_fu_436_p3 = ((tmp_7_fu_378_p2[0:0] === 1'b1) ? p_assign_14_1_cast_fu_372_p2 : p_assign_16_1_fu_384_p2);

assign tmp_s_fu_294_p2 = ((p_014_0_i_reg_260 < ap_const_lv10_2D0) ? 1'b1 : 1'b0);

assign x_fu_600_p3 = ((sel_tmp8_fu_594_p2[0:0] === 1'b1) ? p_p2_i_i_cast_fu_554_p1 : sel_tmp_fu_574_p3);

always @ (posedge ap_clk) begin
    p_Val2_26_0_1_reg_1377[1:0] <= 2'b00;
end

endmodule //Filter2D_1
